version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt-get update -y
      - apt-get install -y nginx
  build:
    commands:
      - echo Copying files to NGINX root
      - cp index.html /var/www/html

artifacts:
  files:
    - '**/*'
